### ISSUE TITLE
Password getting changed even if wrong old password is entered 

### ISSUE THREAD

**Issue by Nikitamisra** [ramankapur/Fonzee-Web#2]
Login the app
click on change password
Enter old password as 'dgfjgdjf' (wrong)
Enter New password and confirm password
Click on submit button

Expected result : Message should be displayed 'wrong Old Password entered '
Actual Result : Password getting changed even if wrong old password is entered

**Comment by adityabandral** [comment]
@Nikitamisra Please check and verify.

**Comment by Nikitamisra** [comment]
verified
